title: wasabi.js
description: >
  write better docuementation with directory structures powered
  by wasabi.js. Simple, readable syntax yields an interactive
  directory structure to help other developers get started on your
  project quick.
baseurl: "/wasabi"
url: "http://atstp.github.io"
markdown: kramdown
permalink: pretty
exclude:
  - "node_modules"
  - "dist"
  - "*_mine_*"

collections:
  demos:
    output: true

defaults:
  - scope:
      path: ""
      type: "demos"
    values:
      layout: demo
